# This is a basic workflow to help you get started with Actions

name: Start SushiShop load tests

on: 
  push:
    branches:
      - master

jobs:
  loadtest:
    name: k6 local test run 
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run k6 local test
      uses: k6io/action@v0.1
      with:
        filename: script2.js
